# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: sybn
brief-intro: "sybn-util 项目说明文档"
baseurl: "/sybn-util" # the subpath of your site, e.g. /blog
url: "http://sybn.gitee.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
email: 354324773@qq.com

description_footer: sybn-util 项目说明文档

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
#duoshuo_shortname: #hygblog
#disqus_shortname: gaohaoyang

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx"; sybnutil:l2TJ
baidu_tongji_id: 51c9b84dabe5fb42e268e952906744fd
google_analytics_id:

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: /category
tag_dir: /tag

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6
